"""ubah nama event menjadi tanggal dan ganti tipe data deskripsi

Revision ID: 04ad6376d8c3
Revises: 488f2b167cb3
Create Date: 2024-07-27 12:37:58.945220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ad6376d8c3'
down_revision = '488f2b167cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal', sa.Date(), nullable=False))
        batch_op.alter_column('deskripsi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('deskripsi',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('tanggal')

    # ### end Alembic commands ###
