"""Change deskripsi to Text type

Revision ID: 488f2b167cb3
Revises: 
Create Date: 2024-07-27 12:25:55.804413

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "488f2b167cb3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deskripsi", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("deskripsi")

    # ### end Alembic commands ###
